services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TORRENTING_PORT=56881
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 8080:8080
      - 56881:56881
      - 56881:56881/udp
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: bitlessbyte/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bookshelf:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}:/data
      - ${CONFIG_PATH}/audiobookshelf:/config
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${MEDIA_PATH}:/data
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mali0:/dev/mali0
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
    restart: unless-stopped
    privileged: true

  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ${CONFIG_PATH}/cloudflared:/etc/cloudflared
      - ${CONFIG_PATH}/cloudflared/cert:/home/nonroot/.cloudflared
    networks:
      - default
      - proxy

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "80:3000"
    volumes:
      - ${CONFIG_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /nas:/nas
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped


  # tdarr:
  #   image: ghcr.io/haveagitgat/tdarr:latest
  #   container_name: tdarr
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - UMASK=002
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - webUIPort=8265
  #     - internalNode=true
  #     - nodeName=Node1
  #   volumes:
      # - ${MEDIA_PATH}:/data
  #     - ${CONFIG_PATH}/tdarr/cache:/temp
  #   devices:
  #     - /dev/mpp_service:/dev/mpp_service
  #     - /dev/rga:/dev/rga
  #     - /dev/dri:/dev/dri
  #     - /dev/dma_heap:/dev/dma_heap
  #     - /dev/mali0:/dev/mali0
  #   ports:
  #     - 8265:8265
  #     - 8266:8266
  #   restart: unless-stopped
  #   privileged: true


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 6767:6767
    restart: unless-stopped


  recyclarr:
      image: ghcr.io/recyclarr/recyclarr:latest
      container_name: recyclarr
      user: ${PUID}:${PGID}
      environment:
        - TZ=${TZ}
      volumes:
        - ${CONFIG_PATH}/recyclarr:/config
      restart: unless-stopped


networks:
  default:
    name: media-server_default
    external: true
  proxy:
    external: true
